# Setup McCoy Group config
title: McCoy Group Notes
description: Little notes and potentially useful bits of info
url: "https://mccoygroup.github.io/Notes" # the base hostname & protocol for your site, e.g. http://example.com
icon: favicon.png
github_username:  McCoyGroup
footer_text: >-
  Brought to you by the McCoy Group at the University of Washington
sitemap_depth: 2
links:
  - url: https://sites.uw.edu/mccoygrp/
    title: Group Website
  - url: https://github.com/McCoyGroup
    title: GitHub
  - url: https://stackoverflow.com/c/mccoygroup/questions
    title: Stack Overflow
  - url: https://mccoygroup.github.io/References/
    title: References

# Build settings
markdown: kramdown
remote_theme: McCoyGroup/finx
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-optional-front-matter
  - jekyll-seo-tag
relative_links:
  enabled: true

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      image: "https://mccoygroup.github.io/References/img/logo_m.png"
      optional_scripts: true
      custom_styles: "refs"
  - scope:
      path: "index.html|about.html|404.html|search.html"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - Documentation/examples
  - Documentation/templates
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
